### ISSUE TITLE
[eng] dashed pronunciations

### ISSUE THREAD

**Issue by kylebgorman** [kylebgorman/wikipron#105]
The English data contains roughly 300-400 entries where the pronunciation is given incompletely, with a dash at the beginning, middle, or end of the entry (usually indicating that we're supposed to fill in the rest of the pronunciation ourselves). Some examples:

    arabica ə - ɹ ă b ĭ - k ə
    observer    ɒ b -
    fornicatory - t o ʊ ɹ i

I would propose that we should remove all these punctuations and can do so on a language-independent basis.

**Comment by lfashby** [comment]
If we want to remove the dashes we could do it as a post-processing step or we could expand `yield_pron()` to do so. `yield_pron()` already removes parentheses. Removing dashes would leave us with entries like this though:
```
personality	i
personality	p ɜː s ə n æ l ə t ɪ
observer	ɒ b
observer	ə b z ɜː v ə
```
Should we filter out entries with a dash instead of just removing the dash?

**Comment by kylebgorman** [comment]
To be very clear, we should remove any entries that contain dashes on the graphemic side---not merely remove the dash.
