### ISSUE TITLE
[ice] semi-duplicate entries

### ISSUE THREAD

**Issue by kylebgorman** [kylebgorman/wikipron#120]
We noticed some duplicate entries in Icelandic such that one has the segmented pronunciation and one doesn't ([example](https://github.com/kylebgorman/wikipron/blob/master/languages/wikipron/tsv/ice_phonemic.tsv#L9614)). We don't yet know where this comes from but it only seems to affect words that begin with þ, and none of these examples seem to have ended up in our Icelandic sample for the paper.

**Comment by kylebgorman** [comment]
Just ran `wikipron icelandic` locally and didn't get the dupes. Must be a one-time issue.

**Comment by lfashby** [comment]
I think I see what has happened. These duplicates were introduced in the second big scrape #95, likely as a result of me failing to resolve certain merge conflicts appropriately. The duplicates are not confined to Icelandic. Our [Polish data](https://github.com/kylebgorman/wikipron/blob/master/languages/wikipron/tsv/pol_phonemic.tsv) is basically full of these duplicates. That is how we have nearly twice as many Polish entries as there are on Wiktionary. 

Most languages don't appear to have any of these duplicates, and the ones that do tend to have less than 10 of them from what I can tell. Assamese and Aramaic have around 1,500. 

This sounds like a good enough excuse to run the big scrape again sometime in the near future, perhaps over winter break?

**Comment by kylebgorman** [comment]
SGTM if you're up to it. Maybe lock it to Jan. 1 or something like that.
