### ISSUE TITLE
[aze] Azerbaijani has three 3 scripts

### ISSUE THREAD

**Issue by lfashby** [kylebgorman/wikipron#121]
Our Azerbaijani data - [phonetic](https://github.com/kylebgorman/wikipron/blob/master/languages/wikipron/tsv/aze_phonetic.tsv), [phonemic](https://github.com/kylebgorman/wikipron/blob/master/languages/wikipron/tsv/aze_phonemic.tsv) - contains Latin, Cyrillic, and Arabic scripts.

**Comment by kylebgorman** [comment]
Looks like only the Latin would survive our 100-entry threshold, but you could write a generalized `aze_split.py` all the same.
