### ISSUE TITLE
[eng] UK phonetic tilde in transcriptions

### ISSUE THREAD

**Issue by lfashby** [kylebgorman/wikipron#126]
Our English UK phonetic data has `~` separating alternate pronunciations similar to `-` which we previously removed. 

Ex: `dance	d æ n s ~ d a n s`

**Comment by kylebgorman** [comment]
I'm not seeing this at head; is this still current?

**Comment by lfashby** [comment]
Yes, it's in a few language. 
[English UK phonetic](https://github.com/kylebgorman/wikipron/blob/master/languages/wikipron/tsv/eng_uk_phonetic.tsv#L549) (21 of them)
[English US phonetic](https://github.com/kylebgorman/wikipron/blob/master/languages/wikipron/tsv/eng_us_phonetic.tsv#L953) (22 of them)
[Persian phonemic](https://github.com/kylebgorman/wikipron/blob/master/languages/wikipron/tsv/per_phonemic.tsv#L196) (72 of them here)
[Kazakh phonetic](https://github.com/kylebgorman/wikipron/blob/master/languages/wikipron/tsv/kaz_phonetic.tsv#L152) (16 of them)
[Icelandic phonemic](https://github.com/kylebgorman/wikipron/blob/master/languages/wikipron/tsv/ice_phonemic.tsv#L1518) (3 of them)
[Italian phonetic](https://github.com/kylebgorman/wikipron/blob/master/languages/wikipron/tsv/ita_phonetic.tsv#L2836) (just 1 of them)
[Hebrew phonemic](https://github.com/kylebgorman/wikipron/blob/master/languages/wikipron/tsv/heb_phonemic.tsv#L887) (2 of them)

**Comment by kylebgorman** [comment]
I suppose our whitelisting approach will keep these out of the data, but I may just go edit them upstream.

**Comment by kylebgorman** [comment]
I'm going to close this and open a new bug just for Persian.
