### ISSUE TITLE
[geo] inconsistencies

### ISSUE THREAD

**Issue by kylebgorman** [kylebgorman/wikipron#138]
The [Wikipedia transcription guidelines](https://en.wikipedia.org/wiki/Help:IPA/Georgian) say that the high front phoneme is /i/ but many transcriptions have /ɪ/ instead. We should fix this upstream (e.g., on Wiktionary itself) and rescrape. 

See [issue](https://github.com/sigmorphon/2020/issues/8) for more context.

**Comment by besou** [comment]
Thanks for your reply! I followed your instructions [here](https://github.com/sigmorphon/2020/issues/8#issuecomment-612875853), scraped all the Georgian data, and added a third column in which I replaced every occurence of /ɪ/ with /i/. The tsv can be found [here](https://github.com/besou/grapheme2phoneme/blob/master/geo.tsv). Since we decided to focus on `i ~ ɪ` for the moment, I left everything else untouched.
(I'm happy to rescrape the updated data once it will be uploaded to Wiktionary and to repeat the process with the velar ~ uvular fricatives `x ~ χ` and `ɣ ~ ʁ` if you like.)

**Comment by kylebgorman** [comment]
>
> Thanks for your reply! I followed your instructions here
> <https://github.com/sigmorphon/2020/issues/8#issuecomment-612875853>,
> scraped all the Georgian data, and added a third column in which I replaced
> every occurence of /ɪ/ with /i/. The tsv can be found here
> <https://github.com/besou/grapheme2phoneme/blob/master/geo.tsv>. Since we
> decided to focus on i ~ ɪ for the moment, I left everything else
> untouched.
> (I'm happy to rescrape the updated data once it will be uploaded to
> Wiktionary and to repeat the process with the velar ~ uvular fricatives x
> ~ χ and ɣ ~ ʁ if you like.)
>

Thanks, that was fast. Can I suggest two things:

* Can you apply the velar/uvular changes also to this?
* Can you remove unaffected words?

I'll try to figure out what the best procedure is to upload this...going to
contact Wiktionary editors re: this; I assume they have a mechanism for
making bulk changes.

K

>

**Comment by besou** [comment]
I have noticed that in the full Georgian data, /ɪ/ is much more frequent (10547) than /i/ (4876). As for the velar-uvular fricatives, the uvular symbols /χ/, /ʁ/ are used slightly more often. The following table indicates the number of changes needed depending on the choice of IPA symbols:

|   | velar | uvular |
|---|-------|--------|
| i | 7356  | 7779   |
| ɪ | 4601  | 3739   |

Overall, the least "destructive" choice would be to take /ɪ/, /χ/, /ʁ/. Should we go with that? I've uploaded a version with this choice [here](https://github.com/besou/grapheme2phoneme/blob/master/geo.tsv).

By the way, for a discussion on the nature of the velar/uvular (postvelar?) fricatives, see [here](http://www.wikiwand.com/en/Talk:Georgian_language/Archive_1#/They_are_postvelar_not_velar_nor_uvular) and also [here](http://www.wikiwand.com/en/Talk:Georgian_language/Archive_1#/Incorrect_Use_of_IPA).

**Comment by kylebgorman** [comment]
I guess my practicing linguistic bias is to use /i, x/ rather than /ɪ, χ/:
I have never heard of a language that had /ɪ/ but doesn't also have a /i
~ ɪ/ contrast, and same with /x ~ χ/, but the other way around would be
unobjectionable. I don't have an opinion on /ɣ ~ ʁ/, so I guess my informal
frequency heuristic is limited and maybe we should just go with the more
frequent ones, as you say.

I'll comment on that talk thread with a link to your work.

**Comment by kylebgorman** [comment]
Made two posts under Talk:

https://en.wiktionary.org/wiki/Category_talk:Georgian_language
https://en.wiktionary.org/wiki/Wiktionary:Information_desk/2020/April#Performing_bulk_edits

Hopefully we'll hear back soon.

**Comment by kylebgorman** [comment]
Apparently we need to [write a bot and then get it approved](https://en.wiktionary.org/wiki/Wiktionary:Bots). They also asked for a Georgian informant to weigh in, so if you have one, please have them do so; if not I have a student who does some work with Georgians and may be able to help.

Anyways, we want to do this for many languages so the practice will be useful.

**Comment by besou** [comment]
> I guess my practicing linguistic bias is to use /i, x/ rather than /ɪ, χ/: I have never heard of a language that had /ɪ/ but doesn't also have a /i ~ ɪ/ contrast, and same with /x ~ χ/, but the other way around would be unobjectionable. I don't have an opinion on /ɣ ~ ʁ/, so I guess my informal frequency heuristic is limited and maybe we should just go with the more frequent ones, as you say. I'll comment on that talk thread with a link to your work.

I would say that when the possible realization of a phoneme spans over the area of multiple IPA symbols, it is mainly a matter of personal choice which IPA symbol one likes to pick as the phoneme. I do not have any preference here, I think both choices are equally valid for each pair.
Personally, I would argue that the preference for /ɪ/, /χ/ in the Georgian transcription might be related to the fact that these two phonemes are clearly more lowered/back than their counterparts /i/ and /x/ in Russian, which of course is an important reference language in the context of Georgian.

> Apparently we need to write a bot and then get it approved. They also asked for a Georgian informant to weigh in, so if you have one, please have them do so; if not I have a student who does some work with Georgians and may be able to help.

I think it would be safer if you could organize to ask a Georgian informant, as this would be an independent confirmation (or rejection) from a clearly different source. But if it's not possible, please let me know.

**Comment by kylebgorman** [comment]
FWIW, it appears that the Wiktionary infrastructure for Georgian prefers
/i, x, ɣ/ so a migration towards those is much easier than the other way
around, and consistency (in phonemic transcriptions) strikes me as much
more important than fine phonetic detail.

I will ask the student whether his informants are available.

**Comment by besou** [comment]
> consistency (in phonemic transcriptions) strikes me as much more important than fine phonetic detail.

Completely agree! I've [updated](https://github.com/besou/grapheme2phoneme/blob/master/geo.tsv) the file to follow the /i, x, ɣ/ preference on Wiktionary.

**Comment by besou** [comment]
The only inconsistency that remains now are transcription errors. For instance, on lines 17-19 you can see the same transcriptions three times, but actually there are consonants omitted at the end (case endings in that particular case), as you can see from looking at the Georgian words. In my initial post, I've also mentioned some other mistakes. Given the regular mapping from Georgian to IPA, it is easy to find and correct these errors, and if you like, I could do that as well (this would probably add some lines to the file because some errors will also be present in words not affected by the /i, x, ɣ/ change).

**Comment by kylebgorman** [comment]
So as per the discussion on Wiktionary, the obvious solution is to develop
[a bot](https://en.wiktionary.org/wiki/Wiktionary:Bots) which moves
Georgian prons to [Template:ka-IPA](
https://en.wiktionary.org/wiki/Template:ka-IPA). Anyone willing to sign up
to work on that?

**Comment by aryamanarora** [comment]
I have [a bot](https://en.wiktionary.org/wiki/User:Aryamanbot) doing that task right now.

**Comment by kylebgorman** [comment]
Great news, thanks.

**Comment by kylebgorman** [comment]
It appears the bot has completed work because I don't see any of /ɪ, χ, ʁ/ anymore. To close this bug we should simply rescrape.
