### ISSUE TITLE
Dialect support in extraction functions

### ISSUE THREAD

**Issue by lfashby** [kylebgorman/wikipron#149]
As mentioned in #146, certain of our extraction functions do not support dialects. 

Currently, dialects are handled by the `_get_pron_xpath_selector` method in `config.py`, the results of which are stored in `pron_xpath_selector`. [`_yield_phn` in our default extraction function ](https://github.com/kylebgorman/wikipron/blob/master/wikipron/extract/default.py#L22) makes use of `config.pron_xpath_selector`, as does [Japanese](https://github.com/kylebgorman/wikipron/blob/master/wikipron/extract/jpn.py#L41) (because its extraction function is used for targeting orthographic entries). 

Our Chinese, Khmer, Latin, and Thai extraction functions do not use the default pron selector and skip over `_yield_phn` by calling [`yield_pron`](https://github.com/kylebgorman/wikipron/blob/master/wikipron/extract/core.py#L23) directly - meaning dialect information is ignored.

**Comment by jacksonllee** [comment]
@kylebgorman @lfashby Should we close this issue? IIRC, we opened this ticket due to not having been able to scrape for Latin by its dialects -- now solved by #233 (Kyle and I stepped through the Latin HTML on Wiktionary together and realized the solution would actually be a lot simpler than we might have expected). Resolving the Latin has led me to think if a language has its custom extraction function and needs dialect support, then it will probably need its own custom solution for dialects as well. There's really no way we can have a generalized solution for dialect specification for languages with custom extraction functions. We can always file more specific tickets for specific languages.

**Comment by kylebgorman** [comment]
+1

**Comment by lfashby** [comment]
I suppose it’s fine to close this. Do we need to make it known somewhere that our `--dialect` flag won't do anything for (certain) languages with extraction functions?

**Comment by jacksonllee** [comment]
> Do we need to make it known somewhere that our --dialect flag won't do anything for (certain) languages with extraction functions?

I don't have a very strong preference, but I feel like this ticket has been serving this purpose, with the problem that this ticket isn't really actionable unless there's another more specific, probably language-particular ticket (like the Latin one). This being said, I could see perhaps a ticket like this is the only sensible thing to do for visibility in our current set-up, given that it's mostly only for developers and would be meaningless in any user-facing documentation for others (e.g. what are the "extraction functions"?).

I'm getting through a couple (known) issues and will update my thoughts here.

**Comment by kylebgorman** [comment]
While a ticket is better than nothing as documentation, I think it would be better if, when using a non-standard scraping procedure (one of the ones that isn't default) we just log that `--dialect` may not work:

https://github.com/kylebgorman/wikipron/blob/master/wikipron/config.py#L176

What do you think?

**Comment by kylebgorman** [comment]
Any thoughts on my proposal @jacksonllee @lfashby ?

**Comment by jacksonllee** [comment]
> I think it would be better if, when using a non-standard scraping procedure (one of the ones that isn't default) we just log that --dialect may not work

This is reasonable. The wording of this logging might be slightly tricky (balancing between giving a warning, not instilling too much fear of things not working, and giving appropriate instructions to report issues if anything arises). I could give this a shot, as this ticket is already assigned to me.

**Comment by kylebgorman** [comment]
SGTM.

**Comment by lfashby** [comment]
I like the logging solution and think that Jackson's PR closing this looks good.
