### ISSUE TITLE
Single-language "big scrape" functionality

### ISSUE THREAD

**Issue by kylebgorman** [kylebgorman/wikipron#153]
Often we want to test changes to one or a small number of languages by running a partial "big scrape" and it would be nice to make this easier to do than making copies of `languages.json`. Maybe something like:

    ./scrape.py --restriction=lit

Would run the scrape for Lithuanian (all dialects and scripts) but would use the appropriate metadata in `languages.json`, and 

    ./scrape.py

would run it for **all** languages in `languages.json`.

**Comment by bonham79** [comment]
Just sent pull with --restriction flag option for one or more languages.
