### ISSUE TITLE
Incorporate whitelisting into `languages.json`

### ISSUE THREAD

**Issue by kylebgorman** [kylebgorman/wikipron#155]
Once #152 is merged we should merge the whitelist functionality into `languages.json`. Presumably it should simply be the case that for any language or dialect if a `whitelist` value is specified, we load it and generate open two TSV files, one for the total data, one for the filtered data. This would also in theory make `whitelist.py` obsolete.

I would suggest that we actually call the unfiltered one a special name or put it somewhere different.

**Comment by bonham79** [comment]
Any particular reason for making it part of languages.json instead of just searching for a whitelist file and defaulting to unfiltered if not found? The search isn't particularly costly and troubleshooting could be limited to checking the whitelist file instead of that and languages.json.

**Comment by kylebgorman** [comment]
That would be fine too I suppose, and an improvement from what we currently have. It's a question of "automagic" vs. explicit configuration.

If you go that route, I would just make sure the log captures useful information from the whitelisting---e.g., that a whitelist was found, how many things were filtered, etc.
