### ISSUE TITLE
Add logging to whitelister

### ISSUE THREAD

**Issue by kylebgorman** [kylebgorman/wikipron#156]
Once #152 is in we should add some kind of logging to the whitelister so we can get a list of "bad" words and the phones that go with them.

Perhaps it should also produce a some kind of structured report (JSON?) instead of just logging.

**Comment by lfashby** [comment]
This looks good, just a few comments.

Regarding logging, I like the idea of a 'structured report' mentioned in #156, but I think this ought to be fine. Perhaps if we direct the logging statements from `whitelist.py` to their own file (as is done with the logging statements generated in `src/scrape.py`) they will be easier to examine/work with? 

Currently this is going to overwrite our old TSV's, which for the time being seems alright and `INPUT_TSV="${WHITELIST//whitelist/tsv}"` is an elegant solution. Eventually maybe we want to keep both the filtered and unfiltered data and give the filtered data a different name as mentioned in #155.
