### ISSUE TITLE
[mlt] Blacklist entries in Arabic script?

### ISSUE THREAD

**Issue by agutkin** [kylebgorman/wikipron#166]
Maltese lexicon has one entry in Arabic script. I suspect it's ended there from an etymology section somewhere. Is there a way to blacklist scripts during scraping?

**Comment by kylebgorman** [comment]
If you add an inner "scripts" dictionary with `"ara"` and `latn` entries, it'll have that effect.

**Comment by agutkin** [comment]
The issue is that Maltese should not have entries in Arabic AFAIK.

**Comment by kylebgorman** [comment]
It'll have that effect. Or if you want to be totally explicit you can say:

   "scripts": { "latn": "Latn" }

We also do something similar, IIRC, to filter out a handful of non-Han entries under Mandarin.

**Comment by agutkin** [comment]
This also drops all the spellings containing the apostrophe (').

**Comment by kylebgorman** [comment]
Oh interesting. This is the ASCII one (0x27)?

If so let's make another bug to track that down. I would have thought
`generalized_split.py` would pass through punctuation (but not space or
dash), but if not it should be easy to add in.

**Comment by agutkin** [comment]
Opened #172.
