### ISSUE TITLE
[got] Handling of reconstructed (unattested) spellings

### ISSUE THREAD

**Issue by agutkin** [kylebgorman/wikipron#189]
Historic languages like Gothic (`got`) contain some pronunciations derived from the [reconstructed](https://github.com/kylebgorman/wikipron/blob/master/data/wikipron/tsv/got_phonemic.tsv) spellings. This reside in `reconstruction:` [namespace](https://en.wiktionary.org/wiki/Wiktionary:Reconstructed_terms)  which ends up in the corresponding spelling prefixes, e.g. `reconstruction:gothic/𐌷𐌻𐌰𐌸𐌰𐌽`.

Some strategy needs to be worked out on how to handle such cases, perhaps by introducing a flag to weed out or keep the reconstructed entries.

**Comment by kylebgorman** [comment]
Agreed. Do you have time to look into this or should we?

**Comment by agutkin** [comment]
I can't look into this this month unfortunately.

**Comment by agutkin** [comment]
What I meant above, if you guys have cycles to look into this that would be great!
