### ISSUE TITLE
[hin] Update required

### ISSUE THREAD

**Issue by warnak** [kylebgorman/wikipron#190]
Currently, the data in the repository notes 8,255 phonemic entries and 214 phonetic entries in Hindi.
But when I used `wikipron hin` on terminal a week ago, I had scraped 8626 entries.

**Comment by kylebgorman** [comment]
@lfashby runs the scraping about twice a year and will probably do so again this fall.

**Comment by warnak** [comment]
hey, didn't know about this, should I close it down then @kylebgorman ?

**Comment by kylebgorman** [comment]
It's up to you, you could leave this open until the next scrape occurs, or
close now.

>
