### ISSUE TITLE
[tyv] Tuvan scraping fails

### ISSUE THREAD

**Issue by kylebgorman** [kylebgorman/wikipron#201]
Not sure why: it looks like it has a Cyrillic orthography and standard IPA phonemic transcriptions: https://en.wiktionary.org/wiki/Category:Tuvan_terms_with_IPA_pronunciation

**Comment by lfashby** [comment]
I'm sure we've encountered things like this before, it's been so long though that it took me a while to track down what was going on! The `iso639` package we use translates 'tyv' into 'Tuvinian', but Wiktionary lists the language name associated with 'tyv' as 'Tuvan'. We are thus targeting a [category](https://github.com/kylebgorman/wikipron/blob/d010afe94fed1912effa247ff6b0c11833449eb7/wikipron/scrape.py#L53) that is empty.
