### ISSUE TITLE
Repo maintenance and upgrades, 2020 edition

### ISSUE THREAD

**Issue by jacksonllee** [kylebgorman/wikipron#235]
Placeholder ticket for a couple repo maintenance tasks we should get to before we make a new release:

* Turn on Python 3.9 support (turn on CircleCI builds for this version, add trove classifier in setup.py)
* Consider adding `black --line-length=79 wikipron tests data` to CircleCI build config to enforce style consistency
* The changelog needs organizing. Consider separating the entries into two categories of something like "data" and "WikiPron package and scraping tools". Update the PR template markdown accordingly.
* Add missing entries to the changelog, if any.
* Check dependency versions (both dev and non-dev packages). Bump versions if appropriate.

**Comment by kylebgorman** [comment]
* I would love also to enable `mypy` and `flake8` on CircleCI. One issue with `flake8` is that it disagrees with `black` on one annoying issue: `black` adds spaces between : slices, and `flake8` complains about them.
* I agree a data sectio nfor the changelog would be wise.
* What about just making a release? We haven't done one in a while.

**Comment by jacksonllee** [comment]
I'm going to write individual, actionable GitHub tickets for the tasks listed in this current ticket. Apparently, it's Hacktoberfest month now and we can label the appropriate tickets with "good first issue" and "hacktoberfest" for anyone looking to contribute, and I'm going to use these labels. This current ticket is meant to be just a discussion thread to collect ideas, not an actionable ticket to be closed by code changes.

* flake8 vs black: I had also run into them not playing nice together recently for other reasons. Though I vaguely remember once all these packages were updated to their latest versions, they appeared to work well together? We will see.
* mypy: I remember we had this conversation before offline. If (the latest version of) mypy doesn't give us more trouble than otherwise, I'd be happy to see it applied in this repo.
