### ISSUE TITLE
Enforce styling consistency with black

### ISSUE THREAD

**Issue by jacksonllee** [kylebgorman/wikipron#237]
Apply `black` for styling consistency. Changes needed:

* Add [`black`](https://pypi.org/project/black/) to `requirements.txt`. Use whatever the latest version is from this PyPI link.
* Add a new `run` step called "Check styling consistency with black" in `.circleci/config.yml`. This new step should go just before the "Run python tests" step. This new step should run the command `black --line-length=79 --check project/setup.py project/wikipron project/tests project/data`.
* If the CircleCI builds fail for this styling check, then the developer will need to update the codebase by applying the command `black --line-length=79 setup.py wikipron tests data` and committing the changes to the associated pull request.
* Add a new entry in `CHANGELOG.md`.

[Guidelines for contributors](https://github.com/kylebgorman/wikipron/blob/master/CONTRIBUTING.md)

**Comment by fakhrip** [comment]
I will try this one...
