### ISSUE TITLE
Restart command with partial extracted data 

### ISSUE THREAD

**Issue by xburelle** [kylebgorman/wikipron#253]
I have use the command line command and, I think, I reached a limit from the server because I was disconnecting and this finished the command.
So it can be useful to continue from a word because data are extracted alphabetically.

**Comment by jacksonllee** [comment]
Thank you for reporting this. Do you by any chance have any logging and/or errors from the terminal that you could copy and share here? Also, how far did the run go (e.g., how many word-pronunciation pairs had been retrieved, if this is known) before you ran into this issue?

**Comment by kylebgorman** [comment]
We also provide [pre-scraped data](https://github.com/kylebgorman/wikipron/tree/master/data) for about 175 languages, and update this periodically (once or twice a year).

**Comment by xburelle** [comment]
Unfortunately, I don't have logs anymore. But I remember it was a "server can't be reached" error. May be my local network or, as I was using wikipron in english and in french at the same time, it can be a security from wiktionary servers. 
I have 32131 lines in english (UK) and 38386 in french, at the end (before the issue appears for both).
Thanks for helping

**Comment by kylebgorman** [comment]
Sometimes the server just hangs up or times out, and this may be one of them. When we do our biannual (twice a year, not once every two years) scrape, we run them in serial because early on we inferred that it was hanging up if we made too many connections.

**Comment by lfashby** [comment]
I’ve been thinking about this problem and something came up that might be the first step toward getting a restart command to work. I can’t recall if we already considered and dismissed trying this months ago...
It is possible to start a scrape from any entry within a language given that you know the `sortkey` for that entry. For example, if I run a scrape of Basque with these parameters:
```
    requests_params = {
        "action": "query",
        "format": "json",
        "list": "categorymembers",
        "cmtitle": category,
        "cmlimit": "500",
        "cmprop": "ids|title|timestamp|sortkey",
        "cmsort": "sortkey", 
        "cmstarthexsortkey": "4e454e44494e0a4e454e44494e"
    }
```
The scrape will start on the word 'nendin' and proceed as normal from there — grabbing the 500 category members after ‘nendin’. Thus if we store the `sortkey` of the most recently scrapped entry (which we have access to given the change to `cmprop` above), and catch whatever error occurs when the connection drops, we ought to be able to automatically restart the scrape from the last `sortkey`. Granted this description is a little bit short on the specifics of how to implement this restart, but I wonder if you think something like this might be possible?

**Comment by kylebgorman** [comment]
I think this would be possible but a lot of work to get right.

You ideally want to make it so that JSON is passed around in a way that
allows one to restart from it. Do you store it in a file or something else?
Who reads it? Does the file live in a special place that it doesn't need to
be specified as an argument? Anyways, I'd need a full design document
before I was willing to endorse any particular proposal, but I don't think
it's crazy.

Maybe to keep it within reasonable scope, you could say this is used just
to restart connections halted due to caught exceptions (except maybe not
control-C interrupts? not sure) within the module, or within the big
scrape, and nothing else?

One last question to think about: would restarting this way cause the
system to print words twice?

**Comment by lfashby** [comment]
Quick question that would help with my restart functionality — can anyone confirm that this intuition is correct:
The only places that we could really timeout or get a connection error would be within `wikipron/scrape.py` either here:
https://github.com/kylebgorman/wikipron/blob/873984edcb67976940820bbddefd7538374871c0/wikipron/scrape.py#L92-L96
or more likely here:
https://github.com/kylebgorman/wikipron/blob/873984edcb67976940820bbddefd7538374871c0/wikipron/scrape.py#L56-L58

Our various `request_html.xpath(…)` just operate on the reply from the server (specifically from that second get request) and don’t make any requests of their own right?

**Comment by kylebgorman** [comment]
I think those `get` calls are the places to expect timeouts, yes. I am not sure about whether `xpath` can get more data or whether it's already materialized but I guess you can guard more stuff later if we turn out to be wrong?
