### ISSUE TITLE
`list_phones.py` should go in `src`, not `phones`?

### ISSUE THREAD

**Issue by kylebgorman** [kylebgorman/wikipron#265]
Proposal; move `list_phones.py` to its parent directory so we don't have a mix of code and data in the same directory. @ajmalanoski @jacksonllee thoughts?

**Comment by jacksonllee** [comment]
> move list_phones.py to its parent directory so we don't have a mix of code and data in the same directory

Sounds good, no strong preference from me.

**Comment by ajmalanoski** [comment]
I agree with the proposal. I think it makes sense to keep the code and data separate.
