### ISSUE TITLE
Python file to filter TSV data

### ISSUE THREAD

**Issue by ajmalanoski** [kylebgorman/wikipron#279]
We've added `list_phones.py` to facilitate the process of making phone lists. Would it make sense to add another script for filtering a language's TSV data based on its .phones file, in order to further facilitate (and standardize) the process?

**Comment by kylebgorman** [comment]
You mean as opposed to scraping new data with `./scrape.py --restriction=yourlang`? I'm weakly opposed: just rescrape it. In the perfect world one would make some upstream changes too to correct errors churned up during the phone list-making project.

**Comment by ajmalanoski** [comment]
Ah, okay. The way I'd been doing it was with a Python script to filter the data we already have (as opposed to re-scraping).

**Comment by kylebgorman** [comment]
On Tue, Dec 1, 2020 at 8:53 PM ajmalanoski <notifications@github.com> wrote:

> Ah, okay. The way I'd been doing it was with a Python script to filter the
> data we already have (as opposed to re-scraping).
>
Oh, I didn’t know, my fault! Try scraping (using data/src/scrape.py) with
the “—restriction” flag. If that’s tedious for some language than yes, good
case for this.

**Comment by ajmalanoski** [comment]
No problem!

Do you think we should edit `data/phones/README.md` so that it says to re-scrape? As it stands, it says to add the filtered TSV file(s), but it doesn't specify how to get them (hence my confusion).

**Comment by kylebgorman** [comment]
Yes, good idea.

**Comment by ajmalanoski** [comment]
Cool, I can take care of that then.
