### ISSUE TITLE
[vie] [ˀ] not transcribed in tones

### ISSUE THREAD

**Issue by ajmalanoski** [kylebgorman/wikipron#280]
The Vietnamese tone represented by <˜> is transcribed on Wiktionary as [˦ˀ˥] for the Hanoi dialect. However, after checking a number of words, it seems that Wikipron did not record the glottalization diacritic (either that, or maybe the Wiktionary transcriptions for all the words I checked have changed since the last time we scraped Vietnamese, but that seems less likely).

As an example, `data/tsv/vie_hanoi_phonetic.tsv` has `bản ngã	ʔ ɓ aː n ˧˩ ŋ aː ˦˥`, but Wiktionary has [ʔɓaːn˧˩ ŋaː˦ˀ˥] as the transcription for [that word](https://en.wiktionary.org/wiki/b%E1%BA%A3n_ng%C3%A3).

**Comment by kylebgorman** [comment]
Can you run `./scrape.py --restriction=vie` and then look to see whether
this persists? The last time I saw an inconsistency like this, it was the
case that the data upstream had changed since last scrape.

**Comment by kylebgorman** [comment]
(I'm running this now too)

**Comment by lfashby** [comment]
Looks like this is a `segments` problem:
```
import segments
tokenizer = segments.Tokenizer()       

print(tokenizer("ʔɓaːn˧˩ ŋaː˦ˀ˥", ipa=True))                                                                                                               
# Prints: ʔ ɓ aː n ˧˩ # ŋ aː ˦˥
```
(`#` is from the space in the transcription, `ˀ` is dropped for some reason.)

**Comment by kylebgorman** [comment]
Good sleuthing.

Segments is a constant problem. I wonder if we should just fork it and do
our own thing.

**Comment by lfashby** [comment]
I submitted a PR to the `segments` guys regarding this. We'll see what they say. If they do accept it should I ask them to do a pypi release?

**Comment by kylebgorman** [comment]
Yes, that’d be the next step.
