### ISSUE TITLE
[arm] can you keep original capitalization?

### ISSUE THREAD

**Issue by jhdeov** [kylebgorman/wikipron#300]
On the scraped Armenian [data](https://github.com/kylebgorman/wikipron/blob/master/data/tsv/arm_e_phonetic.tsv), you have entries like
> աաակ |  ɑ ɑ ɑ k
աֆրիկա | ɑ f ɾ i k ɑ

But in the original Wiktionary entries, words like աաակ are actually acronyms and all uppercase [ԱԱԱԿ](https://en.wiktionary.org/wiki/%D4%B1%D4%B1%D4%B1%D4%BF). And words like աֆրիկա are proper names and start uppercase [Աֆրիկա](https://en.wiktionary.org/wiki/%D4%B1%D6%86%D6%80%D5%AB%D5%AF%D5%A1). It would be useful if your scraping and script maintained the original capitalization for words. That way, if someone wants to find the pronunciation of all acronyms (or exclude acronyms), then they can just filter over the shape of the word. Benefits for this are also that acronyms and proper names tend to display different phonological behavior than other normal words.

Edit: Sorry in the original comment, I linked to the Armenian entries on Armenian wiktionary -____-

**Comment by kylebgorman** [comment]
I don't think this is a good idea; it's not done consistently cross-linguistically, and we don't have "intel" for the 160-odd languages about how consistently it's done (say, if I wanted to find out P(titlecase | proper name) for Armenian, how would I compute that except via painstaking human annotation?). If need be you can just generate this locally. In tech-industry-scale speech work we generally assume upstream capitalization is useless, and I think that's generally the right assumption.

**Comment by jhdeov** [comment]
That makes sense. Though would it make sense if you add it as a parameter to your script? Something like

> wikipron arm --keep-original-case

Because the Armenian wiktionary entries already are using capitalization for the headwords, like [ԱԱԱԿ](https://en.wiktionary.org/wiki/%D4%B1%D4%B1%D4%B1%D4%BF)

**Comment by kylebgorman** [comment]
That's the default. No need to specify it. Case-folding of the orthographic
form is enabled using `--casefold`.

**Comment by jhdeov** [comment]
Ah! I didn't know that because the `-h` help command didn't explain what casefolding was. Thanks :D  (I just googled it now to know what the word case-folding means, and oddly the word `case` wasn't mentioned in your ACL paper)

So to clarify, the default is to maintain capitalization (case-folding is off by default). It may be helpful if in your datasets, you provide both the original non-casefolded forms alongside a casefolded forms (whether in the same file or different files).

**Comment by kylebgorman** [comment]
That's something we could do---not a bad feature request---but it'd double
the time it takes to generate the big scrape files, which is already 7-8
days.

**Comment by jhdeov** [comment]
Understood. I guess it's more feasible for a per-user basis, i.e., I just do it for myself for Armenian (and post it on my own Github) and be on my merry way. I think an alternative is to just explain that in the README because it was pretty opaque to me what was going on with the case-folding and capitalization until I reverse-engineered it from your dataset files.

Sorry, I was writing my comments while you were closing the thread :/
