### ISSUE TITLE
[arm] missing Western Armenian entries

### ISSUE THREAD

**Issue by jhdeov** [kylebgorman/wikipron#301]
Hi again

I think your Western Armenian [dataset](https://github.com/kylebgorman/wikipron/blob/master/data/tsv/arm_w_phonetic.tsv) is missing a lot of words (potentially almost all of them). For example, this [word](https://en.m.wiktionary.org/wiki/%D5%A3%D6%80%D5%BA%D5%A1%D5%B6) has a Western pronunciation on Wiktionary but it's not on your dataset. 

I suspect the problem is that most of the Armenian transcriptions are all generated via a [script](https://en.wiktionary.org/wiki/Module:hy-pronunciation) (explained [here](https://github.com/kylebgorman/wikipron/issues/298)) whereby:
1. A wiktionary user writes a transcription using the Armenian script
2. The script then converts the transcription into IPA for Eastern and Western Armenian.
The users use this script because for a large chunk of the lexicon, it's predictable to go from the Eastern pronunciation towards the Western one via a series of sound changes.

It looks like your code just stops at capturing the Eastern transcription and doesn't then capture the Western transcription.

**Comment by kylebgorman** [comment]
I think that's changed in the last 5 months. It's working fine now when I
try from command line now so that entry probably didn't exist with the
multiple pronunciations before. (We're aware that a lot of pron entries are
generated by server-side script. That's another reason we can't just use
the backend: we need the HTML not just the MediaWiki data.)

**Comment by jhdeov** [comment]
Oh... That explains why [Wiktextract](https://github.com/tatuylonen/wiktextract) could only pull [arm] words without their pronunciations. Huh, go figure.

I look forward to your eventual scrape :D

**Comment by lfashby** [comment]
It looks like our Armenian dialect support (both Western and Eastern) is currently broken. Based on the [word](https://en.wiktionary.org/wiki/%D5%A3%D6%80%D5%BA%D5%A1%D5%B6) initially linked to in this issue (and checking a few other Armenian entries) we'd need to change our dialects in `languages.json` to:
```
        "dialect": {
            "w": "Western Armenian, standard",
            "e": "Eastern Armenian, standard"
        }
```
It doesn't look as though there are any entries that list the dialect as "Western Armenian" or "Eastern Armenian" anymore. I'm not sure if this is something we care about fixing on our end, but it's good to be aware of before the next big scrape.

**Comment by kylebgorman** [comment]
As it happens I noticed the same, and am I'm working on this in a PR right
now. Thanks Lucas.

**Comment by jhdeov** [comment]
Around this summer, the main people who handle the Armenian entries did an overhaul of their script documentation and application, including changing the names I think.
