### ISSUE TITLE
Automatic script inspection

### ISSUE THREAD

**Issue by lfashby** [kylebgorman/wikipron#319]
Our current `data`-side method for handling languages that use multiple (orthographic) scripts is to manually specify in [`languages.json`](https://github.com/kylebgorman/wikipron/blob/master/data/src/languages.json) that multiple scripts will be present in TSVs for certain languages. [`split.py`](https://github.com/kylebgorman/wikipron/blob/master/data/src/split.py) then separates these scripts into different TSVs such that each TSV only contains one script.

The process of manually inspecting TSVs/Wiktionary to figure out if a language uses multiple scripts is so 2020 and ideally should be replaced by something that can automatically inspect each file in `data/tsv` and tell us whether more than one (Unicode) script is present and, if more than one script is present, what the Unicode script names are for each present script. For the time being, I imagine that the code running this automatic inspection should be placed in `tests/test_data`. If we manage to write something that can do this automatic inspection we can decide if it should be thoroughly integrated into the `data` side later.

This would be a cool (though I anticipate difficult to implement) feature. It’s a bit of a wonder that this technology doesn’t already exist, or perhaps it does and I haven’t found it. People have worked on things like it – see [this stackoverflow issue](https://stackoverflow.com/questions/9868792/find-out-the-unicode-script-of-a-character), I haven’t evaluated `unicodedata2`, mentioned in that SO post, but maybe it is what we need – and you can check the section of `split.py` below to get acquainted with a method that uses the `regex` package to separate TSVs according to an inputted script property. Perhaps the `regex` package can also be used to ‘discover’ the script property of characters in each TSV?
https://github.com/kylebgorman/wikipron/blob/370d8d1442604c2590def43c502fef5a52c79468/data/src/split.py#L12-L17

**Comment by kylebgorman** [comment]
@agutkin this would be interesting to you, I think.

**Comment by agutkin** [comment]
Out of curiosity - is regex package using ICU under the hood?

**Comment by kylebgorman** [comment]
Just read the code and I don't see any mention of ICU, so I think no.
