### ISSUE TITLE
Latin phones list not functional

### ISSUE THREAD

**Issue by lfashby** [kylebgorman/wikipron#325]
[`data/phones/lat_phonemic.phones`](https://github.com/kylebgorman/wikipron/blob/master/data/phones/lat_phonemic.phones) needs to be split into three separate lists (`lat_clas_phonemic.phones`, `lat_vulg_phonemic.phones`, etc.) in accordance with its dialects in order to be used by `src/scrape.py`.

I'd imagine this is low-priority and perhaps this list was originally just added as a demonstration(?) but it currently doesn't do anything.

**Comment by kylebgorman** [comment]
I'll do this.
