### ISSUE TITLE
Covering grammar naming

### ISSUE THREAD

**Issue by ajmalanoski** [kylebgorman/wikipron#385]
As it stands, the covering grammar files in `data/cg/tsv` are just named `<lng>.tsv`, where `<lng>` is the three-letter language code. I think the file names should for the CGs should match those used for the data they correspond to, that is, they should phonetic/phonemic status and script name.

**Comment by kylebgorman** [comment]
+1

**Comment by ajmalanoski** [comment]
On a related note, the `.phones` files also do not include the script in their filenames. They probably should, though, right? @kylebgorman

**Comment by kylebgorman** [comment]
No, don't think they need that, since they only refer to the pron side?

**Comment by ajmalanoski** [comment]
Oh duh, very true
