### ISSUE TITLE
Phonemic/phonetic vs. broad/narrow

### ISSUE THREAD

**Issue by ajmalanoski** [kylebgorman/wikipron#389]
I think that we should reconsider the naming conventions for our data, change "phonemic" and "phonetic" to "broad" and "narrow," respectively. First, I think it would more accurately represent the nature of our data. Second, it would reduce the possibility of mixing up the two types of data. Third, I think the "broad/narrow" distinction is more transparent to non-linguists than "phonemic/phonetic" (since the "broad" and "narrow" are used to refer to level of detail in non-technical vocabulary, e.g. "broadly speaking," "narrowly defined") Finally, you would get the nice bonus of autofilling with the tab key in the command line much sooner.

**Comment by kylebgorman** [comment]
+1

**Comment by kylebgorman** [comment]
Closed in #402.
