### ISSUE TITLE
[khm] Khmer / [tha] Thai / [chi] Chinese support

### ISSUE THREAD

**Issue by lfashby** [kylebgorman/wikipron#56]
Both [khm] Khmer and [tha] Thai pull no data in phonetic or phonemic mode. 

Both languages list their transcriptions within tables. 

[Khmer example](https://en.wiktionary.org/wiki/%E1%9E%80%E1%9E%B6%E1%9E%9B%E1%9E%9C%E1%9E%B7%E1%9E%97%E1%9E%B6%E1%9E%82#Khmer)
[Thai example](https://en.wiktionary.org/wiki/%E0%B8%81%E0%B8%A3%E0%B8%B0%E0%B8%94%E0%B8%B9%E0%B8%81#Thai)

**Comment by lfashby** [comment]
[chi] Chinese runs into a similar problem in that the pages for each word entry are not formatted in the same way as other languages. Additionally, it seems most of the word entries do not contain a phonetic or phonemic transcription and instead link to a different page which may or may not have an IPA transcription.

**Comment by jacksonllee** [comment]
@lfashby @kylebgorman Any thoughts on having a separate ticket for each language and close this current one? It seems to me that (surprise, surprise) every language has its own quirks, and potentially needs a separate ticket for discussion. Also, cleaner repo management, etc.
* Thai has tone letters in IPA, which is irrelevant for Khmer.
* Chinese is a whole other can of worms, as the entries each have a table that contain IPA for multiple Chinese languages (cf. my comment [here](https://github.com/kylebgorman/wikipron/issues/57#issuecomment-539296420)).

**Comment by kylebgorman** [comment]
Yes, these should all be separate tickets.
