### ISSUE TITLE
[eng, spa]: dialect specifications

### ISSUE THREAD

**Issue by kylebgorman** [kylebgorman/wikipron#66]
In the current checked-in `languages.json` there is no dialect specification for either English or Spanish, whereas the earlier Bash script had one (and we want one).

For `eng`: `--dialect="US | General American"`
For `spa`:  `--dialect="Latin America"`

**Comment by kylebgorman** [comment]
Once completed we want to run the scraping again for those two.

As a future step it would be good to have both British and US/GenAm English, and both Castillian/European and Latin American Spanish as separate TSVs/data sets.

**Comment by lfashby** [comment]
Do you have a preference for either of these?
1. Including `require_dialect_label` for all languages (in languages.json) and setting it to false for all languages except `eng` and `spa`.
2. Omitting `require_dialect_label` for all languages except `eng` and `spa`.

(Setting `require_dialect_label` to true requires specifying a `dialect` config option as well. If we go with 1 above, then shall I also include an empty `dialect` config option for all languages?)

Neither options is better than the other when it comes to how to handle scraping for dialects in the big scrape so it really just comes down to how we want to format languages.json. 1 is perhaps better if we will be adding dialect specification to more languages in the future, 2 makes languages.json look nicer and takes advantage of config.py default settings.

**Comment by jacksonllee** [comment]
Hmm, now I'm wondering if this third option may make sense: Simply remove the `require_dialect_label` option from the package altogether, i.e., if `dialect` is specified, scrape for the dialect(s) in question, otherwise just scrape for everything (whether or not the entry has a dialect label). I can see this would be a breaking change, and that we would lose the ability to scrape for all entries that explicitly have at least one dialect label, but then now I don't see why this would be useful anymore. Thoughts?

**Comment by kylebgorman** [comment]
Yeah, I'm struggling to remember what the `--require_dialect_label` flag was for in the first place. Either you want to scrape a dialect (or a union of dialects), or you want to scrape everything; why would you want to scrape all labeled data but don't want to specify from which dialect? If we can't think of a good  answer, let's remove the flag.

**Comment by jacksonllee** [comment]
I've just opened #75 for removing the "require dialect label" option. In general, I can help remove all obstacles for the upcoming big scrape, so that Lucas can focus on prep and config for the scrape run.
