### ISSUE TITLE
[scraping] Support all config options

### ISSUE THREAD

**Issue by kylebgorman** [kylebgorman/wikipron#68]
The scraping should support all config options including cut-off date, and then next big scrape run should use, IDK, 11/1/2019 as a cutoff date?

**Comment by lfashby** [comment]
How should I handle the new `no_segment` option? Will we always want it set to its default value of false for all languages? If that's the case, do I need to include it at all in languages.json or can we just rely on the config.py default settings?

My inclination is to not include the `phonetic` config option, as to me part of the purpose of big scrape is to always try to scrape in both phonetic and phonemic settings for each language. 

Specifying an `output` config option prompts Wikipron to create a file that doesn't get written to (when using Wikipron from python).

**Comment by jacksonllee** [comment]
For `no_segment`, I think we should leave it unspecified and let `Config` use its default settings.

+1 for getting both phonetic and phonemic data for each language. Not including `phonetic` in `languages.json` sounds good to me.

> Specifying an output config option prompts Wikipron to create a file that doesn't get written to (when using Wikipron from python).

Gah, this is a bug! I've opened #74 for this.

**Comment by kylebgorman** [comment]
+1 to using default values whenever possible.

+1 to not using `phonetic` in the config.

Thanks for #74 Jackson---I was vaguely under the impression we'd taken care of that already?

**Comment by lfashby** [comment]
Looking at the `_get_cut_off_date()` code in `config.py` I'm reminded I think of why I didn't use it in the original big scrape. 
If you don't specify `cut_off_date` then `_get_cut_off_date()` will generate one for you  `today = datetime.date.today()`.
If you do specify `cut_off_date` and it is later than todays date, ("2019-11-01", for example) it throws an error.
```
if d > today:
    msg = (
        "Cut-off date cannot be later than today's date: "
        f"{cut_off_date}"
    )
    raise ValueError(msg)
```
Is this the desired behavior? Wouldn't it make more sense to throw an error when `d < today`? Perhaps I am missing something.

**Comment by jacksonllee** [comment]
Yeah, the current behavior of `_get_cut_off_date()` is intended. The idea is to have more stable scrape results. Say today is Oct 23rd and the user specifies Oct 1st as the cut-off date, this would mean you get results as of Oct 1st. IIRC, the cut-off date is our approximation of "versioned" data (assuming that once a word or something is added to Wiktionary, no-one is going to remove it, which seems like a reasonable assumption). When Kyle suggested 11/1/2019 as a possible cut-off date above, my interpretation was that we'll do the big scrape _after_ this date when all necessary fixes are hopefully in and ready at that point.

**Comment by lfashby** [comment]
I see, I neglected to look at how it is being used in `_get_process_word()`. 

My bad.

**Comment by jacksonllee** [comment]
No, not your fault. I could have documented these things better -- I'll update the help text in the CLI for `cut_off_date` in one of my upcoming PR's. Your questions have been super helpful in improving the codebase. Please do keep them coming!
