### ISSUE TITLE
[tha] Thai support

### ISSUE THREAD

**Issue by lfashby** [kylebgorman/wikipron#71]
Thai IPA transcriptions are within tables. [Example](https://en.wiktionary.org/wiki/%E0%B8%81%E0%B8%A3%E0%B8%B0%E0%B8%94%E0%B8%B2%E0%B8%99%E0%B8%96%E0%B8%B5%E0%B8%9A#Thai)

This is related to the issue in #70 regarding Khmer in that the solution offered for scraping Khmer (creating a new selector template) looks like it would work for scraping Thai. 

Thai IPA transcriptions also include tones. Does this present a problem? Are there pre- or post-processing steps that we are considering for handling languages that use IPA tones?

**Comment by jacksonllee** [comment]
For tone, I'm inclined to think we should handle it like other suprasegmental information such as stress and syllable boundaries. So we could add a `--no-tone` CLI arg, similar to the current `--no-stress` and `--no-syllable-boundaries`, and then add a processor function like [these](https://github.com/kylebgorman/wikipron/blob/abecf0341268a9426e489226599ae8881c02aaf3/wikipron/config.py#L172-L175).

**Comment by kylebgorman** [comment]
Let's preserve tone for now; can add `--no-tone` later.
