### ISSUE TITLE
[jpn] Japanese support

### ISSUE THREAD

**Issue by jacksonllee** [kylebgorman/wikipron#73]
Bringing over the discussion on Japanese from #62...

* Which script(s) should we target? Head words of Japanese entries on Wiktionary could be in Kana, Kanji, or a mix of both? Do we filter or not? Or do we want some sort of post-processing like what's being planned for Serbo-Croatian (#62)?
* In parallel with the WIkiPron package, there's [this prior work](https://github.com/kylebgorman/wikipron/blob/abecf0341268a9426e489226599ae8881c02aaf3/languages/jpn_wik/scrape.py) by Alan/Kyle for scraping Japanese specifically. Maybe incorporate this into WikiPron somehow?

@lfashby @kylebgorman Please edit or comment as you see fit.

**Comment by kylebgorman** [comment]
Implementationally, instead of targeting `Category:${language}_terms_with_IPA_pronunciation" we want to target `Category:Japanese_katakana` and/or `Category:Japanese_hiragana` (the mapping between the two is not exactly 1-to-1 but it's very close).
