### ISSUE TITLE
`output` has no effect in API usage

### ISSUE THREAD

**Issue by jacksonllee** [kylebgorman/wikipron#74]
Lucas has reported the following in https://github.com/kylebgorman/wikipron/issues/68#issuecomment-544209039:

> Specifying an output config option prompts Wikipron to create a file that doesn't get written to (when using Wikipron from python).

This is a bug, as it means the `output` option (for specifying whether scraped data is in a text file or in stdout) has inconsistent behavior being CLI and API usage:
* CLI: operational as documented
* API: no effect

Two options:

1. Make the exposed `scrape` function call use the `output` option somehow to match the CLI behavior, i.e., if `output` is used, pipe the results to the specified text file and return `None, but if not used, then just yield the <word, pron> pairs (= current behavior).
2. Remove the `output` option completely. For CLI usage, if a user wants data in a text file, they could redirect stdout by `>`, like `$ wikipron fra > fra.tsv` (which we would document in the readme). From this perspective, the `output` option seems unnecessary.

Relatedly, I'm pretty open to improving WikiPron by making breaking changes at this early stage, as I'm suggesting another breaking change now, see https://github.com/kylebgorman/wikipron/issues/66#issuecomment-544214656). For this current ticket, I have a slight preference for just removing the `output` option, since this would mean keeping the `scrape` function behave in only one way (i.e., for always yielding the <word, pron> pairs, and not having an alternative behavior of returning `None`).

**Comment by kylebgorman** [comment]
I would weakly prefer #2, getting rid of the `output` option. `stdout` is great and we should use it.
