### ISSUE TITLE
Handle the tie bar for affricates in IPA segmentation

### ISSUE THREAD

**Issue by jacksonllee** [kylebgorman/wikipron#78]
IPA segmentation doesn't appear to correctly handle the tie bar for affricates. For instance, from https://github.com/kylebgorman/wikipron/pull/76#discussion_r339324885, I saw the following for Brazilian Portuguese:

```tsv
adição a d͡ ʒ i s ɐ̃ w
```

Instead, we would want the following for this example:

```tsv
adição a d͡ʒ i s ɐ̃ w
```

**Comment by m-sean** [comment]
this seems like a job for the parser i wrote! happy to submit a pull request for it to resolve the issue.
