### ISSUE TITLE
[kxd] Brunei (Malay) not in languagecodes.json

### ISSUE THREAD

**Issue by lfashby** [kylebgorman/wikipron#84]
Trying to scrape for Brunei (ISO 639 name; Brunei Malay is the Wiktionary name) led to the following error. 

>   File ".../wikipron/config.py", line 128, in _get_language
>     language = iso639.to_name(key).split(";")[0]
>   File ".../lib/python3.7/site-packages/iso639/__init__.py", line 115, in to_name
>     raise NonExistentLanguageError('Language does not exist.')
> iso639.NonExistentLanguageError: Language does not exist.

Brunei Malay's code is "kxd" which is ISO 639-3 only, meaning it isn't covered by the iso639 package we are using. 

For the time being I'll just go ahead and add `"kxd": "Brunei Malay"` myself to languagecodes.py. Perhaps it should be added in a separate pull request from the one I'll eventually submit with all the new data?
 I'm not sure how this happened, shouldn't this have been caught by test_languagecodes.py? (Unless someone added 228 entries to Brunei Malay since test_languagecodes.py was last run.)

**Comment by jacksonllee** [comment]
> I'm not sure how this happened, shouldn't this have been caught by test_languagecodes.py? (Unless someone added 228 entries to Brunei Malay since test_languagecodes.py was last run.)

FWIW, the master branch (updated 2 days ago) is now associated with [this build for the Python 3.6 run](https://circleci.com/gh/kylebgorman/wikipron/198?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), with the following warnings:

```
tests/test_languagecodes.py::test_language_coverage
  /root/project/tests/test_languagecodes.py:97: UserWarning: WikiPron cannot handle "Brunei Malay".
    warnings.warn(f'WikiPron cannot handle "{language}".')

tests/test_languagecodes.py::test_language_coverage
  /root/project/tests/test_languagecodes.py:97: UserWarning: WikiPron cannot handle "Mecayapan Nahuatl".
    warnings.warn(f'WikiPron cannot handle "{language}".')
```

The `languagecodes.py` module was added maybe ~2 months ago, without Brunei Malay or Mecayapan Nahuatl. So it's probably true that the community has been adding pronunciation entries to Wiktionary from time to time, and that some languages which didn't pass the threshold of >= 100 pronunciation entries before now do and trigger the warning in the build.

> For the time being I'll just go ahead and add "kxd": "Brunei Malay" myself to languagecodes.py. Perhaps it should be added in a separate pull request from the one I'll eventually submit with all the new data?

+1 for just adding these unhandled language codes to `languagecodes.py` now and keep the scrape run going. The fix seems to be relatively small and straightforward (as opposed to something much more involved like the alternative HTML / XPath parsing needed for other languages, in which case I'd say we should in general apply the "use try-except to wrap and log anything that would stop the big scrape" strategy, report the issue, and resolve it separately).

**Comment by lfashby** [comment]
I see. Thanks for the insight into that 'build' page, I looked at it a few times when I was submitting pull requests but didn't really understand what was going on.
