### ISSUE TITLE
[khb] Lü support

### ISSUE THREAD

**Issue by lfashby** [kylebgorman/wikipron#86]
From Wiktionary: 
> Lü is a Southwestern Tai language spoken mainly in Yunnan province, China.

Lü has 301 entries on Wiktionary but we were only able to scrape [one](https://en.wiktionary.org/wiki/%E1%A8%BE%E1%A9%AE%E1%A9%A5%E1%A9%A0%E1%A8%A6#L%C3%BC). This look to be another problem with our `_LI_SELECTOR_TEMPLATE`. It seems all entries but the one we scraped have title set as `title="Appendix:Lü pronunciation (page does not exist)"`. Here is an [example](https://en.wiktionary.org/wiki/%E1%A6%82%E1%A7%81%E1%A7%89#L%C3%BC). The sole entry we scraped has title set as `title="wikipedia:Lü phonology"`

I'd imagine fixing this is a very low priority, but I figured it is something we should be aware of.

**Comment by kylebgorman** [comment]
Closed by #219
