### ISSUE TITLE
Add a --no-tone flag

### ISSUE THREAD

**Issue by jacksonllee** [kylebgorman/wikipron#91]
Thai (#71) was handled by #90, but we'd still like a `--no-tone` flag to optionally remove the IPA tones.

**Comment by kylebgorman** [comment]
+1. Wonder if this should default to false?

**Comment by jacksonllee** [comment]
> Wonder if this should default to false?

Yes, it'd be the same treatment like `--no-stress` and `--no-syllable-boundaries` that we already have (so with `action="store_true"` in the CLI argparse set-up).

In general, I think our API design should be "if the user wants to _remove_ information, they should be forced to do something, e.g., explicitly applying a flag to say so".

**Comment by jacksonllee** [comment]
Also, a note about what "tone" means for our purposes --

1. The IPA tone letters like `˧`, as used for the Thai entries.
2. The Chao tone numbers like `⁵`, as used for Chinese languages (cf. #72, #57).
3. The accents, as widely used for Bantu languages ([example from Chichewa](https://en.wiktionary.org/wiki/beseni#Chichewa)).

The `--no-tone` flag for removing tone would have to handle all these cases.

**Comment by kylebgorman** [comment]
Super cool that the IPA decided not to standardize any of those! ;)

**Comment by lfashby** [comment]
Looking at Jackson's Chichewa example in the comment above I'm wondering if Chichewa is like Latin or like Serbo-Croatian. The headwords often don't have tone diacritics, but the words on each entry page do.

Here is a line from the [about Chichewa](https://en.wiktionary.org/wiki/Wiktionary:About_Chichewa) page that makes me think it is like Serbo-Croatian:
> Entries when linked to or mentioned should not show tone unless there is reason to do so (for example, to distinguish words whose only difference is tone).
