### ISSUE TITLE
Serbo-Croatian pitch accents

### ISSUE THREAD

**Issue by lfashby** [kylebgorman/wikipron#98]
Somewhat like Latin (#80) Serbo-Croatian headwords largely don't match the word given on the page. The headwords are not given with accent diacritics. 
[Cyrillic example](https://en.wiktionary.org/wiki/%D0%BD%D0%B0%D1%98%D0%BB%D0%BE%D0%BD#Serbo-Croatian)
[Latin example](https://en.wiktionary.org/wiki/para#Serbo-Croatian)

Here's a quote from the [Serbo-Croatian phonology page](https://en.wikipedia.org/wiki/Serbo-Croatian_phonology#Pitch_accent):
> Accent diacritics are not used in the ordinary orthography, but only in the linguistic or language-learning literature (e.g. dictionaries, orthography and grammar books). However, there are very few minimal pairs where an error in accent can lead to misunderstanding. 

Is it important to us to grab the words with accents, or can we get away with just grabbing the headword? (The people putting together the Serbo-Croatian Wiktionary IPA category [elected](https://en.wiktionary.org/wiki/Wiktionary:About_Serbo-Croatian#The_headword) to omit accents from the headword.)

**Comment by kylebgorman** [comment]
IMO, let's omit them. Same thing is true in Russian (where there are actually thousands of minimal pairs). Part of the fun in those languages.

**Comment by kylebgorman** [comment]
Still thinking about this. It's a bit different from classical languages where diacriticization techniques evolved during the postclassical period but have become the standard way to read the language (e.g., polytonic Ancient Greek was invented in the late Byzantine period; Latin macronization caught on in the early modern). There is nothing comparable in Russian or S-C.

**Comment by lfashby** [comment]
Sounds good to me, wasn't aware that this was also the case in Russian. 

Closing.
