### ISSUE TITLE
lat.py does not casefold

### ISSUE THREAD

**Issue by lfashby** [kylebgorman/wikipron#99]
While working on Japanese I noticed that `lat.py` in the `extract` directory does not call `config.casefold` on the extracted words. I checked our most recent Latin data and indeed, despite `casefold` being set to true in languages.json, the data is not all lower case. 

This should be an easy fix but I'm submitting the issue because we will need to run Latin again.

**Comment by jacksonllee** [comment]
Ah, my bad -- I'll take this one.
